"""
generate_pdf_report.py
Builds a professional-looking automated PDF report from the scored batches --
this is the "dashboards/reports" + "automation" piece of the JD, turning raw
model output into something a QC manager could actually read and act on.
"""

import pandas as pd
from pathlib import Path
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                 TableStyle, Image, PageBreak)

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
CHARTS_DIR = BASE_DIR / "charts"
REPORTS_DIR = BASE_DIR / "reports"
REPORTS_DIR.mkdir(exist_ok=True)

df = pd.read_csv(DATA_DIR / "scored_batches.csv")

styles = getSampleStyleSheet()
title_style = styles["Title"]
heading_style = styles["Heading2"]
body_style = ParagraphStyle("body", parent=styles["Normal"], fontSize=10, leading=14)
note_style = ParagraphStyle("note", parent=styles["Normal"], fontSize=8,
                             textColor=colors.grey, leading=11)

story = []

# ---- Title block ----
story.append(Paragraph("Batch Quality Risk Report", title_style))
story.append(Paragraph(
    f"Generated {datetime.now().strftime('%d %B %Y, %H:%M')} &nbsp;|&nbsp; "
    f"Prototype AI/ML pipeline &mdash; synthetic data demonstration",
    note_style))
story.append(Spacer(1, 16))

# ---- Summary ----
total = len(df)
flagged = df["flagged_for_review"].sum()
high = (df["risk_level"] == "High").sum()
medium = (df["risk_level"] == "Medium").sum()
low = (df["risk_level"] == "Low").sum()

summary_text = (
    f"Of <b>{total}</b> incoming batches scored, <b>{flagged}</b> were flagged for "
    f"manual QC review before proceeding further in the process "
    f"({high} High risk, {medium} Medium risk, {low} Low risk). "
    f"Flagging is based on a model-estimated failure probability, using a decision "
    f"threshold tuned to prioritize catching true failures over minimizing false alarms."
)
story.append(Paragraph("Summary", heading_style))
story.append(Paragraph(summary_text, body_style))
story.append(Spacer(1, 14))

# ---- Flagged batches table ----
story.append(Paragraph("Batches Flagged for Review", heading_style))

flagged_df = df[df["flagged_for_review"]].copy()
table_data = [["Batch ID", "Fail Prob (%)", "Risk", "Machine", "Shift", "Mixing (min)", "Humidity (%)"]]
for _, row in flagged_df.iterrows():
    table_data.append([
        row["batch_id"], f"{row['fail_probability']:.1f}", row["risk_level"],
        row["machine_id"], row["operator_shift"],
        f"{row['mixing_time_min']:.1f}", f"{row['humidity_pct']:.1f}",
    ])

if len(flagged_df) == 0:
    story.append(Paragraph("No batches were flagged in this run.", body_style))
else:
    t = Table(table_data, repeatRows=1, hAlign="LEFT")
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4472C4")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F2F2F2")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(t)

story.append(Spacer(1, 18))

# ---- What drives these predictions ----
story.append(Paragraph("What Drives These Predictions", heading_style))
story.append(Paragraph(
    "The model weighs several process factors together. Historically (in the training "
    "data), the strongest signals were: machine M4, night shift operation, longer mixing "
    "times, and higher humidity. The chart below shows relative feature importance from "
    "the trained model.", body_style))
story.append(Spacer(1, 8))
story.append(Image(str(CHARTS_DIR / "feature_importance.png"), width=5.5 * inch, height=3.9 * inch))

story.append(PageBreak())

# ---- Model performance appendix ----
story.append(Paragraph("Appendix: Model Performance", heading_style))
story.append(Paragraph(
    "For reference, this report is generated by a Logistic Regression model "
    "(selected over a Random Forest alternative for better ROC-AUC), evaluated on a "
    "held-out test set of real (synthetic) outcomes:", body_style))
story.append(Spacer(1, 8))

perf = pd.read_csv(BASE_DIR / "models" / "model_comparison.csv", index_col=0)
perf_row = perf.loc["Logistic Regression"]
perf_table_data = [
    ["Metric", "Value"],
    ["ROC-AUC", f"{perf_row['roc_auc']:.3f}"],
    ["Accuracy", f"{perf_row['accuracy']:.3f}"],
    ["Precision (Fail)", f"{perf_row['precision']:.3f}"],
    ["Recall (Fail)", f"{perf_row['recall']:.3f}"],
    ["Decision threshold", f"{perf_row['threshold']:.3f}"],
]
pt = Table(perf_table_data, hAlign="LEFT", colWidths=[2.2 * inch, 1.5 * inch])
pt.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4472C4")),
    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ("FONTSIZE", (0, 0), (-1, -1), 9.5),
    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
    ("TOPPADDING", (0, 0), (-1, -1), 5),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
]))
story.append(pt)
story.append(Spacer(1, 10))
story.append(Paragraph(
    "Note: built on synthetic data designed to reflect realistic manufacturing "
    "relationships, as a demonstration of the full pipeline -- not on real plant data.",
    note_style))

doc = SimpleDocTemplate(str(REPORTS_DIR / "batch_qc_report.pdf"), pagesize=letter,
                         topMargin=0.6 * inch, bottomMargin=0.6 * inch)
doc.build(story)
print(f"Report saved -> reports/batch_qc_report.pdf")
