"""
score_batches.py
Loads the trained model (saved in Day 1) and scores the new incoming batches
generated by generate_new_batches.py -- this is the "automation" step: turning
a trained model into something that acts on new data without manual re-work.
"""

import pandas as pd
import joblib
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
MODELS_DIR = BASE_DIR / "models"

# Load the saved pipeline + tuned threshold (both saved together in Day 1)
bundle = joblib.load(MODELS_DIR / "qc_model.joblib")
pipeline = bundle["pipeline"]
threshold = bundle["threshold"]

new_batches = pd.read_csv(DATA_DIR / "new_batches.csv")

feature_cols = ["mixing_time_min", "temperature_C", "humidity_pct",
                 "moisture_content_pct", "raw_material_lot_age_days",
                 "operator_shift", "machine_id"]

fail_probability = pipeline.predict_proba(new_batches[feature_cols])[:, 1]
new_batches["fail_probability"] = (fail_probability * 100).round(1)
new_batches["flagged_for_review"] = fail_probability >= threshold

# A simple 3-tier risk label -- easier for a non-technical reader (or QC team)
# to act on than a raw probability number
def risk_tier(p):
    if p >= threshold:
        return "High"
    elif p >= threshold * 0.6:
        return "Medium"
    return "Low"

new_batches["risk_level"] = fail_probability.round(3)
new_batches["risk_level"] = [risk_tier(p) for p in fail_probability]

new_batches = new_batches.sort_values("fail_probability", ascending=False)
new_batches.to_csv(DATA_DIR / "scored_batches.csv", index=False)

flagged = new_batches[new_batches["flagged_for_review"]]
print(f"Scored {len(new_batches)} incoming batches (threshold={threshold:.2f})")
print(f"{len(flagged)} batch(es) flagged for manual review:\n")
print(flagged[["batch_id", "fail_probability", "risk_level", "machine_id", "operator_shift"]]
      .to_string(index=False))
print("\nFull results saved -> data/scored_batches.csv")
